;;; package --- Summary
;; -*- lexical-binding: t; -*-

;;; Commentary:
;; This theme defines a "minimalistic" theme based on reddish, pastel tints, and a VSCode theme called Alabaster, albeit dark and red. This theme features a primary color, a secondary color, and a highlight which most other colors are based off from.

;;; Code:
(require 'autothemer)

(autothemer-deftheme
 crypt "A minimalistic theme based on Alabaster (coolest theme concept) and a reddish pastel tint."
 ((((class color) (min-colors #xFFFFFF)))

  ;; Defines Color palette
  (crypt-primary "#3C2A33")
  (crypt-secondary "#C5C5C5")
  (crypt-highlight "#FFDEF0")
  (crypt-string "#FF7F7F")
  (crypt-comment "#FF6347")
  (crypt-constant "#D0D060")
  (crypt-warning "#FF0000")
  (crypt-global-def "#FFC080")
  (crypt-punctuation "#737C8C"))

 ;; Customize faces
 ((default                                   (:foreground crypt-secondary :background crypt-primary :family "Fantasque Sans Mono" :height 130))
  (cursor                                    (:background crypt-highlight))
  (region                                    (:background "#5a3f4d"))
  (font-lock-string-face                     (:foreground crypt-string))
  (font-lock-comment-face                    (:foreground crypt-comment))
  (font-lock-escape-face                     (:foreground crypt-constant))
  (font-lock-constant-face                   (:foreground crypt-constant))
  (font-lock-number-face                     (:foreground crypt-constant))
  (font-lock-function-name-face              (:foreground crypt-global-def))
  (font-lock-variable-name-face              (:foreground crypt-secondary))
  (font-lock-keyword-face                    (:foreground crypt-constant))
  (font-lock-type-face                       (:foreground crypt-secondary))
  (font-lock-builtin-face                    (:foreground crypt-secondary))
  (font-lock-operator-face                   (:foreground crypt-secondary))
  (font-lock-warning-face                    (:foreground crypt-warning))
  (font-lock-function-call-face              (:foreground crypt-secondary))
  (mode-line                                 (:foreground crypt-highlight :background "#261010" :box (:line-width 4 :color "#261010") :height 150))
  (mode-line-inactive                        (:foreground "#a3a3a3" :background "#261010" :box (:line-width 4 :color "#261010") :height 140))
  (header-line                               (:foreground crypt-highlight :background "#261010" :box (:line-width 4 :color "#261010") :height 140))
  (font-lock-punctation-face                 (:foreground crypt-punctuation))
  (show-paren-match                          (:background "#ff5dae" :weight 'extra-bold))
  (fringe                                    (:background crypt-primary))
  (rainbow-delimiters-depth-1-face           (:foreground "#FF6347"))
  (rainbow-delimiters-depth-2-face           (:foreground "#FFA07A"))
  (rainbow-delimiters-depth-3-face           (:foreground "#FF7F7F"))
  (rainbow-delimiters-depth-4-face           (:foreground "#FFD700"))
  (rainbow-delimiters-depth-5-face           (:foreground "#FF4500"))
  (rainbow-delimiters-depth-6-face           (:foreground "#B22222"))
  (rainbow-delimiters-depth-7-face           (:foreground "#8B0000"))
  (rainbow-delimiters-depth-8-face           (:foreground "#800000"))
  (rainbow-delimiters-depth-9-face           (:foreground "#A52A2A"))
  (rainbow-delimiters-unmatched-face         (:foreground crypt-warning))
  (rainbow-delimiters-mismatched-face        (:foreground crypt-warning))
  (hl-line                                   (:background "#271920"))
  (org-level-1                               (:foreground "#FF7F7F"))
  (org-level-2                               (:foreground "#FFD700"))
  (org-level-3                               (:foreground "#FF6347"))
  (org-level-4                               (:foreground "#FFA500"))
  (org-level-5                               (:foreground "#FF0000"))
  (org-level-6                               (:foreground "#B22222"))
  (org-level-7                               (:foreground "#8B0000"))
  (org-level-8                               (:foreground "#800000"))
  (message-mml                               (:foreground crypt-highlight))
  (minibuffer-prompt                         (:foreground crypt-highlight))
  (vertico-posframe                          (:background "#261010" :height 0.5))
  (vertico-posframe-border                   (:background "#261010"))
  (shr-text                                  (:inherit 'default))
  (org-document-info                         (:foreground "#FFA07A" :weight 'bold))
  (org-document-title                        (:foreground "#FF6347" :weight 'ultra-bold :underline t))
  (org-todo                                  (:foreground "#ff2a95" :weight 'bold))
  (org-headline-todo                         (:foreground "#ff2a95"))
  (org-done                                  (:foreground "#36252e" :weight 'bold))
  (org-headline-done                         (:foreground "#36252e"))
  (vertico-posframe-border-fallback          (:background crypt-global-def))
  (shr-link                                  (:foreground crypt-highlight))
  (indent-guide-face                         (:foreground crypt-highlight))
  (highlight                                 (:background "#271920"))
  (org-dispatcher-highlight                  (:foreground crypt-global-def))
  (org-table                                 (:foreground crypt-highlight))
  (match                                     (:foreground "#FF6347"))
  (button                                    (:foreground "#FFA500" :underline t))
  (org-cite                                  (:foreground "#FF6347" :underline t))
  (org-cite-key                              (:foreground "#FFE4B2" :underline t))
  (org-date                                  (:foreground "#FF6347" :underline t))
  (org-link                                  (:foreground "#FF6347" :underline t))))

(provide-theme 'crypt)
;;; crypt-theme.el ends here
