;;; mines-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mines.el

(autoload 'mines "mines" "\
Play the minesweeper game.
Called with a prefix prompt for the difficulty level.

(fn &optional ARG)" t)
(register-definition-prefixes "mines" '("mines-"))

;;; End of scraped data

(provide 'mines-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mines-autoloads.el ends here
