;;; insecure-lock-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from insecure-lock.el

(autoload 'insecure-lock-enter "insecure-lock" "\
Toggle on screen lock." t)
(register-definition-prefixes "insecure-lock" '("insecure-lock-"))

;;; End of scraped data

(provide 'insecure-lock-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; insecure-lock-autoloads.el ends here
