;;; io-mode-inf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from io-mode-inf.el

(autoload 'io-run-io "io-mode-inf" "\
Run a Io interpreter in an Emacs buffer

(fn &optional CMD-LINE)" t)
(autoload 'io-switch-to-interpreter "io-mode-inf" "\
Switch to buffer containing the interpreter" t)
(autoload 'io-eval-region "io-mode-inf" "\
Send current region to io interpreter.

(fn START END)" t)
(autoload 'io-eval-buffer "io-mode-inf" "\
Send whole buffer to Io interpreter." t)
(autoload 'io-load-file "io-mode-inf" "\
Load a file in the Io interpreter.

(fn FILE-NAME)" t)
(autoload 'io-quit-interpreter "io-mode-inf" "\
Quit io interpreter." t)
(register-definition-prefixes "io-mode-inf" '("io-"))

;;; End of scraped data

(provide 'io-mode-inf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; io-mode-inf-autoloads.el ends here
