;;; academic-phrases-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from academic-phrases.el

(autoload 'academic-phrases "academic-phrases" "\
Insert a phrase from a list of academic phrases by topic." t)
(autoload 'academic-phrases-by-section "academic-phrases" "\
Insert a phrase from a list of academic phrases by the paper section." t)
(register-definition-prefixes "academic-phrases" '("academic-phrases--"))

;;; End of scraped data

(provide 'academic-phrases-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; academic-phrases-autoloads.el ends here
