;;; brainfuck-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from brainfuck-mode.el

(autoload 'brainfuck-mode "brainfuck-mode" "\
Major mode for brainfuck

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.bf\\'" . brainfuck-mode))
(langdoc-define-help-mode bf-help "Major mode for brainfuck help" "\
*Brainfuck Help*" 'bf-help-sym-called-at-point '(">" "<" "+" "-" "." "," "[" "]") 'bf-help-lookup-doc "`\\([^']+\\)'" (lambda (a b) b) (lambda (a b) b) "`" "'")
(register-definition-prefixes "brainfuck-mode" '("bf-" "brainfuck-mode-local-map" "define-bf-keymap"))

;;; End of scraped data

(provide 'brainfuck-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; brainfuck-mode-autoloads.el ends here
