;;; blackjack-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from blackjack.el

(autoload 'blackjack "blackjack" "\
Run Blackjack." t)
(register-definition-prefixes "blackjack" '("blackjack-"))

;;; End of scraped data

(provide 'blackjack-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; blackjack-autoloads.el ends here
