;;; io-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from io-mode.el

(autoload 'io-mode "io-mode" "\
Major mode for editing Io language...

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.io$" . io-mode))
(register-definition-prefixes "io-mode" '("io-"))

;;; End of scraped data

(provide 'io-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; io-mode-autoloads.el ends here
