;;; flappymacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flappymacs.el

(autoload 'flappymacs "flappymacs" "\
Play flappybird and waste time.

flappymacs-mode keybindings:\\<flappymacs-mode-map>

\\{flappymacs-mode-map}" t)
(register-definition-prefixes "flappymacs" '("flappymacs-"))

;;; End of scraped data

(provide 'flappymacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flappymacs-autoloads.el ends here
